apiVersion: v1
kind: Service
metadata:
  name: springboot-jenkins-docker-service
spec:
  selector:
    app: springboot-jenkins-docker
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30620
  type: NodePort
