services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8082:8080"
    volumes:
      - jenkins-home:/var/jenkins-home
    environment:
      - JENKINS_INSTALL_PLUGINS=workflow-aggregator,maven-plugin
    restart: always
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data/sonatype-work
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M
    restart: always

volumes:
  jenkins-home: {}
  nexus-data: {}