services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - jenkins-home:/var/jenkins-home
    environment:
      - JENKINS_INSTALL_PLUGINS=workflow-aggregator,maven-plugin
    restart: always
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8082:8081"	
    volumes:
      - nexus-data:/nexus-data/sonatype-work
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2703M -Xmx2703M -XX:MaxDirectMemorySize=2703M
    restart: always
  jdk:
    image: openjdk:17
    command: /bin/bash -c "curl -L -X GET 'http://host.docker.internal:8082/service/rest/v1/search/assets/download?sort=version&repository=nexus-release&group=com.danilo&name=springboot-jenkins-docker&maven.baseVersion=0.0.5' -o /app/springboot-jenkins-docker.jar && java -Dspring.profiles.active=k8s -jar /app/springboot-jenkins-docker.jar"
    ports:
      - "8080:8080"
    volumes:
      - jdk-data:/app

volumes:
  jenkins-home: {}
  nexus-data: {}
  jdk-data: {}