apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-jenkins-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-jenkins-docker
  template:
    metadata:
      labels:
        app: springboot-jenkins-docker
    spec:
      restartPolicy: Always
      containers:
        - name: nexus
          image: sonatype/nexus3
          envFrom:
            - configMapRef:
                name: springboot-jenkins-docker-configmap
      imagePullSecrets:
        - name: nexus-key
