apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-jenkins-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-jenkins-docker
  template:
    metadata:
      labels:
        app: springboot-jenkins-docker
    spec:
      restartPolicy: Always
      containers:
        - name: nexus
          image: sonatype/nexus3
          envFrom:
            - configMapRef:
                name: springboot-jenkins-docker-configmap
          command: ["java"]
          args:
            [
              "-jar",
              "-Dspring.profiles.active=k8s",
              "http://host.docker.internal:8082/service/rest/repository/browse/nexus-release/com/danilo/springboot-jenkins-docker/0.0.1/springboot-jenkins-docker-0.0.1.jar",
            ]
      imagePullSecrets:
        - name: nexus-key
